# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:45
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 11, 15, 45, 1, 135876, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items_brand_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='brand',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_items_brand_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='brand',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 11, 15, 45, 7, 302934, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items_item_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_items_item_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 11, 15, 45, 10, 559336, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items_order_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_items_order_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 11, 15, 45, 18, 902346, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items_purchase_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_items_purchase_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 11, 15, 45, 22, 591021, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items_store_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='store',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='store',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_items_store_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='store',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
    ]
