# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_audit_log_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created']},
        ),
    ]
