# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.Location'),
            preserve_default=False,
        ),
    ]
